export type Vec3 = { x: number; y: number; z: number };
export type AnchorMap = Record<string, [number, number, number]>;
export type SpiderState = {
  mode: string;
  status: string;
  estop: boolean;
  armed: boolean;
  controller_ready: boolean;
  controller_detail: string | null;
  geometry_valid: boolean;
  workspace_valid: boolean;
  calibration_valid: boolean;
  faults: string[];
  warnings: string[];
  last_error: string | null;
  homed: Record<string, boolean>;
  limits_verified: boolean;
  motor_direction_ok: Record<string, boolean>;
  zero_lengths_m: Record<string, number>;
  line_offsets_steps: Record<string, number>;
  controller_trace: string[];
  position: Vec3;
  target: Vec3;
  speed: number;
  anchors: AnchorMap;
  bounds: { x: [number, number]; y: [number, number]; z: [number, number] };
  lengths: Record<string, number>;
  target_lengths: Record<string, number>;
  steps: Record<string, number>;
  spools: Record<string, number>;
  trail: Vec3[];
  path: { name: string | null; index: number; points: Vec3[] };
  updated_at: number;
};
